import { useQuery } from "@tanstack/react-query";

import {
  getAvailabilityDayDetail,
  getAvailabilityHeatmap,
  getLatestAvailability,
  getLatestPrices,
  getPriceTimeseries,
  getSources,
  getViatorListing,
} from "@/api/market";
import { dashboardQueryKeys } from "@/features/dashboard/queryKeys";

export function useSourcesQuery(tourCode: string | null) {
  return useQuery({
    queryKey: dashboardQueryKeys.sources(tourCode ?? ""),
    queryFn: ({ signal }) => getSources(tourCode ?? "", signal),
    enabled: Boolean(tourCode),
    staleTime: 10 * 60 * 1000,
    gcTime: 30 * 60 * 1000,
    placeholderData: (previousData) => previousData,
  });
}

export function useLatestPricesQuery(
  tourCode: string | null,
  horizonDays: number,
  rangeDays?: number,
  otaName?: string,
) {
  return useQuery({
    queryKey: dashboardQueryKeys.latestPrices(tourCode ?? "", horizonDays, rangeDays, otaName),
    queryFn: ({ signal }) =>
      getLatestPrices({
        tourCode: tourCode ?? "",
        horizonDays,
        rangeDays,
        otaName,
        signal,
      }),
    enabled: Boolean(tourCode),
    staleTime: 45 * 1000,
    gcTime: 10 * 60 * 1000,
    refetchInterval: 3 * 60 * 1000,
    placeholderData: (previousData) => previousData,
  });
}

export function useLatestAvailabilityQuery(
  tourCode: string | null,
  horizonDays: number,
  rangeDays?: number,
  otaName?: string,
) {
  return useQuery({
    queryKey: dashboardQueryKeys.latestAvailability(tourCode ?? "", horizonDays, rangeDays, otaName),
    queryFn: ({ signal }) =>
      getLatestAvailability({
        tourCode: tourCode ?? "",
        horizonDays,
        rangeDays,
        otaName,
        signal,
      }),
    enabled: Boolean(tourCode),
    staleTime: 45 * 1000,
    gcTime: 10 * 60 * 1000,
    refetchInterval: 3 * 60 * 1000,
    placeholderData: (previousData) => previousData,
  });
}

export function usePriceTimeseriesQuery(
  tourCode: string | null,
  horizonDays: number,
  fromDate?: string,
  toDate?: string,
) {
  return useQuery({
    queryKey: dashboardQueryKeys.priceTimeseries(tourCode ?? "", horizonDays, fromDate, toDate),
    queryFn: ({ signal }) =>
      getPriceTimeseries({
        tourCode: tourCode ?? "",
        horizonDays,
        fromDate,
        toDate,
        limit: 50_000,
        signal,
      }),
    enabled: Boolean(tourCode),
    staleTime: 2 * 60 * 1000,
    gcTime: 15 * 60 * 1000,
    placeholderData: (previousData) => previousData,
  });
}

/** Histórico del mes calendario: no filtra por horizon_days en la API (mezcla scrapes de distintos horizontes). */
export function usePriceTrendTimeseriesQuery(tourCode: string | null, fromDate: string, toDate: string) {
  return useQuery({
    queryKey: dashboardQueryKeys.priceTimeseriesTrend(tourCode ?? "", fromDate, toDate),
    queryFn: ({ signal }) =>
      getPriceTimeseries({
        tourCode: tourCode ?? "",
        fromDate,
        toDate,
        limit: 50_000,
        signal,
      }),
    enabled: Boolean(tourCode) && Boolean(fromDate) && Boolean(toDate) && fromDate <= toDate,
    staleTime: 2 * 60 * 1000,
    gcTime: 15 * 60 * 1000,
    placeholderData: (previousData) => previousData,
  });
}

export function useAvailabilityHeatmapQuery(
  tourCode: string | null,
  params: {
    otaName?: string;
    fromDate?: string;
    toDate?: string;
    rangeDays?: number;
  },
) {
  return useQuery({
    queryKey: dashboardQueryKeys.availabilityHeatmap(
      tourCode ?? "",
      params.otaName,
      params.fromDate,
      params.toDate,
      params.rangeDays,
    ),
    queryFn: ({ signal }) =>
      getAvailabilityHeatmap({
        tourCode: tourCode ?? "",
        otaName: params.otaName,
        fromDate: params.fromDate,
        toDate: params.toDate,
        rangeDays: params.rangeDays,
        signal,
      }),
    enabled: Boolean(tourCode),
    staleTime: 60 * 1000,
    gcTime: 15 * 60 * 1000,
    placeholderData: (previousData) => previousData,
  });
}

export function useAvailabilityDayDetailQuery(tourCode: string | null, targetDate: string | null, otaName?: string) {
  return useQuery({
    queryKey: dashboardQueryKeys.availabilityDayDetail(tourCode ?? "", targetDate ?? "", otaName),
    queryFn: ({ signal }) =>
      getAvailabilityDayDetail({
        tourCode: tourCode ?? "",
        targetDate: targetDate ?? "",
        otaName,
        signal,
      }),
    enabled: Boolean(tourCode && targetDate),
    staleTime: 60 * 1000,
    gcTime: 15 * 60 * 1000,
    placeholderData: (previousData) => previousData,
  });
}

/**
 * Fetches the Viator listing snapshot served by GET /viator/listing.
 * The snapshot is generated by `scraping/viator/listing_scraper.py`.
 * Re-fetches every 10 minutes; stale after 5 minutes.
 */
export function useViatorListingQuery() {
  return useQuery({
    queryKey: dashboardQueryKeys.viatorListing(),
    queryFn: ({ signal }) => getViatorListing(signal),
    staleTime: 5 * 60 * 1000,
    gcTime: 30 * 60 * 1000,
    refetchInterval: 10 * 60 * 1000,
    // Never block rendering — we treat the listing as an optional enrichment
    placeholderData: (previousData) => previousData,
    retry: 1,
  });
}
